minimumReleaseAge: 1440 # 24 hours
minimumReleaseAgeExclude:
  - "@tanstack/react-router*"
  - "@tanstack/react-start*"
  - "@tanstack/router-*"
  - "@tanstack/start-*"
  - "react-dom"
  - "react"
saveExact: true
