minimumReleaseAge: 1440 # 24 hours
minimumReleaseAgeExclude:
  - "@tanstack/react-router*"
  - "@tanstack/react-start*"
  - "@tanstack/router-*"
  - "@tanstack/start-*"
  - "react-dom"
  - "react"
  # Renovate security update: devalue@5.6.4
  - devalue@5.6.4
saveExact: true
